TodoApp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("application/",include("application.urls"))
]

application/urls.py
from django.urls import path
from . import views

app_name="application"

urlpatterns=[
    path("",views.indexView.as_view(),name="index"),
    path("regist/",views.registView.as_view(),name="regist"),
    path("login/",views.LoginView.as_view(),name="login"),
    path("target_list/",views.TargetListView.as_view(),name="target_list"),
    path("target_list/<str:day>/",views.TargetRegistView.as_view(),name="target_regist"),
    path("target_update/",views.get_update_target,name="get_update_target"),
    path("target_update/<int:pk>",views.TargetUpdateView.as_view(),name="target_update"),
    path("target_delete/<int:pk>",views.TargetDeleteView.as_view(),name="target_delete"),
    #path("target_update/<str:update>",views.TargetUpdateView.as_view(),name="target_update"),
    #path("target_regist/",views.TargetRegistView.as_view(),name="target_regist"),
    path("target_get/",views.get_targets,name="target_get"),
    path("logout/",views.LogoutView.as_view(),name="logout"),
]

application/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import (
    AbstractBaseUser,PermissionsMixin,BaseUserManager
)

# Create your models here.



class UserManager(BaseUserManager):
    def create_user(self,username,email,password=None):
        if not email:
            raise ValueError(" Enter Email ")
        
        user=self.model(
            username=username,
            email=email
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

class Users(AbstractBaseUser,PermissionsMixin):
    username=models.CharField(max_length=150)
    email=models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    objects=UserManager()

    class Meta:
        db_table="users"

class Target(models.Model):
    user=models.ForeignKey(Users,on_delete=models.CASCADE)
    title=models.CharField(max_length=150,blank=False,null=False)
    memo=models.TextField(blank=True,null=True)
    start=models.DateField(default=timezone.now)
    deadline=models.DateField(default=timezone.now)
    clear=models.BooleanField(default=False)

    class Meta:
        db_table="target"

application/views.py
import os
import json
import time
import datetime
from typing import Any, Dict
from django import http

from django.utils import timezone

from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import (
    CreateView,FormView,UpdateView,DeleteView
)
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, JsonResponse,Http404
from django.contrib import messages

from .form import (
    UserRegistForm,LoginForm,TargetRegistForm,TargetUpdateForm,
)
from .models import Target


# Create your views here.

class indexView(TemplateView):
    template_name=os.path.join("application","index.html")

class registView(CreateView):
    template_name=os.path.join("application","regist.html")
    form_class=UserRegistForm

    success_url=reverse_lazy("application:index")

class LoginView(FormView):
    template_name=os.path.join("application","login.html")
    form_class=LoginForm

    def post(self,request,*args,**kwargs):
        form=LoginForm(request.POST)
        email=request.POST["email"]
        password=request.POST["password"]
        user=authenticate(email=email,password=password)
        next_url=request.POST["next"]
        if user is not None and user.is_active:
            login(request,user)
            if next_url:
                return redirect(next_url)
            return redirect("application:index")
        else:
            form.add_error(None, 'メールアドレス、またはPASSWORDが違います。')
            return render(request,"application/login.html",{'form': form})
        
class LogoutView(FormView):
    def get(self,request,*args,**kwargs):
        logout(request)
        return redirect("application:login")
        
class TargetListView(LoginRequiredMixin,TemplateView):
    template_name=os.path.join("application","target_list.html")

class TargetRegistView(LoginRequiredMixin,CreateView):
    template_name=os.path.join("application","target_regist.html")
    form_class=TargetRegistForm

    def post(self,request,*args,**kwargs):
        form=TargetRegistForm(request.POST)
        title=request.POST.get("title")
        memo=request.POST.get("memo")
        start=request.POST["start"]
        deadline=request.POST["deadline"]
        user=request.user
        target=Target(user=user,title=title,memo=memo,start=start,deadline=deadline)
        if title is not None:
            target.save()
        else:
            return render(request,"application/target_regist.html",{'form': form})
        return redirect("application:target_list")

    success_url=reverse_lazy("application:target_list")

class TargetUpdateView(LoginRequiredMixin,UpdateView):
    template_name=os.path.join("application","target_update.html")
    form_class=TargetUpdateForm
    model=Target
    success_url=reverse_lazy("application:target_list")

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context=super().get_context_data(**kwargs)
        context["pk"]=context["target"].id
        return context#ここを変更してhtmlでpkを受け取れるようにする

class TargetDeleteView(LoginRequiredMixin,DeleteView):
    template_name=os.path.join("application","target_delete.html")
    model=Target
    success_url=reverse_lazy("application:target_list")
    

def target_regist(request):
    return render(request,"application/regist.html")

def get_targets(request):

    if request.method=="GET":
        return Http404()
    
    datas = json.loads(request.body)
    
    start=datas["start_date"]
    deadline=datas["end_date"]

    user=request.user

    formatted_start_date = time.strftime(
        "%Y-%m-%d", time.localtime(start / 1000))
    formatted_end_date = time.strftime(
        "%Y-%m-%d", time.localtime(deadline / 1000))

    target=Target.objects.filter(
        start__lt=formatted_end_date,deadline__gt=formatted_start_date,user=user
    )

    list = []
    for t in target:
        color="rgb(204, 204, 204)" if t.clear else "rgb(83, 187, 195)"
        list.append(
            {
            "title": t.title,
            "start": t.start,
            "end": t.deadline,
            "clear":t.clear,
            "color":color,
            }
        )

    return JsonResponse(list,safe=False)

def get_update_target(request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        form=TargetUpdateForm(request.GET)
        start=int(request.GET.get("start"))
        title=request.GET.get("title")

        user=request.user

        formatted_start_date = time.strftime(
            "%Y-%m-%d", time.localtime(start / 1000))

        target=Target.objects.filter(
            start=formatted_start_date,user=user,title=title
        )

        t=target.first()

        return redirect("application:target_update",pk=t.id)

templates/application/index.html
{% extends "base.html" %}

{% block content %}
<h1>ホーム画面</h1>
{% endblock %}

templates/application/login.html
{% extends "base.html" %}
{% load static %}

{% block css%}
<link rel="stylesheet" href="{% static 'css\index.css' %}">
{% endblock %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    <input type="submit" value="ログイン">
</form>

{% endblock %}

templates/application/regist.html
{% extends "base.html" %}
{% load static %}

{% block css%}
<link rel="stylesheet" href="{% static 'css\index.css' %}">
{% endblock %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="ユーザ登録">
</form>

{% endblock %}

templates/application/target_delete.html
{% extends "base.html" %}
{% load static %}

{% block css%}
<link rel="stylesheet" href="{% static 'css\index.css' %}">
{% endblock %}

{% block content %}
<h2>予定を削除しますがよろしいですか?</h2>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="削除">
</form>
{% endblock %}

{% block javascript%}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'javascript/regist.js' %}"></script>
{% endblock %}

templates/application/target_list.html
{% extends "base.html" %}
{% load static %}

{% block css%}
<link rel="stylesheet" href="{% static 'css\index.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.css">
{% endblock %}

{% block content %}

<div id='calendar'></div>

{% endblock %}

{% block javascript%}

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.js"></script>
<script src="{% static 'javascript/app.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/locale/ja.js"></script>
{% endblock %}

templates/application/target_regist.html
{% extends "base.html" %}
{% load static %}

{% block css%}
<link rel="stylesheet" href="{% static 'css\index.css' %}">
{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="目標設定">
</form>
{% endblock %}

{% block javascript%}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'javascript/regist.js' %}"></script>
{% endblock %}

templates/application/target_update.html
{% extends "base.html" %}
{% load static %}

{% block css%}
<link rel="stylesheet" href="{% static 'css\index.css' %}">
{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="情報更新">
</form>
<a href="{% url 'application:target_delete' pk=pk %}">削除する</a>
{% endblock %}

{% block javascript%}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'javascript/regist.js' %}"></script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css\index.css' %}">
    {% block css %}{% endblock %}
    <title>Document</title>
</head>
<body>

<header class="header">
<div class="header__container">
{% if user.is_authenticated %}
<a href="{% url 'application:target_list' %}">カレンダー</a>

<a href="{% url 'application:logout' %}">ログアウト</a>
{% else %}
<a href="{% url 'application:regist' %}">登録</a>
<a href="{% url 'application:login' %}">ログイン</a>
{% endif %}
</div>
</header>
{% block content %}
{% endblock %}
{% block javascript %}
{% endblock %}
</body>
</html>